[package]
name = "image-sorter"
version = "0.1.0"
authors = ["Jorge Galat <jrgglt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
tui = { version = "0.9.4", features = ["termion"], default-features = false }
termion = "1.5.5"
subprocess = "0.2.6"
